apiVersion: v2
name: microservice3
description: AI engine for video processing
version: 1.0.18
appVersion: 1.0.18
keywords:
  - microservice3
  - nextensio
  - platform9
home: https://github.com/nextensio/helm-charts/demos_platform9_microservice3
maintainers:
- name: nextensio
  email: support@nextensio.com
type: application
kubeVersion: ">=1.16.0-0"
